name: CulinaryAddict
favicon: null
layout_spectrum: 0.6281898838933557
typography_spectrum: 0.8996448630932719
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.35067436937242746
  lightness: 0.901807333342731
  saturation: 0.5874628524761647
  rhythmicContrast: 0.6909338664263487
purpose: []
