name: CulinaryAddict
favicon: null
layout_spectrum: 0.50544
typography_spectrum: 0.24955
title: Culinary Addicts Diary
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0907'
    - '#fefefe'
    - '#f40000'
    - '#515151'
    - '#db696b'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
